const crypto = require("crypto");
const fs = require("fs");
const path = require("path");

const envPath = path.join(__dirname, "..", ".env");

if (fs.existsSync(envPath)) {
  console.log("[OK] cms/.env already exists");
  process.exit(0);
}

const secret = () => crypto.randomBytes(16).toString("base64");

const content = `# Auto-generated by setup-cms-env.bat — local dev only
HOST=0.0.0.0
PORT=1337

APP_KEYS=${[secret(), secret(), secret(), secret()].join(",")}
API_TOKEN_SALT=${secret()}
ADMIN_JWT_SECRET=${secret()}
TRANSFER_TOKEN_SALT=${secret()}
JWT_SECRET=${secret()}
ENCRYPTION_KEY=${secret()}

STRAPI_PLUGIN_I18N_INIT_LOCALE_CODE=ko

DATABASE_CLIENT=sqlite
DATABASE_FILENAME=.tmp/data.db
`;

fs.writeFileSync(envPath, content, "utf8");
console.log("[OK] Created cms/.env with new APP_KEYS");
